
- name: Generate a list of secrets with random content
  set_fact:
    secrets_list:
      - mosip_abis_client_secret
      - mosip_admin_client_secret
      - mosip_admin_services_client_secret
      - mosip_auth_client_secret
      - mosip_crereq_client_secret
      - mosip_creser_client_secret
      - mosip_creser_idpass_client_secret
      - mosip_datsha_client_secret
      - mosip_deployment_client_secret
      - mosip_digitalcard_client_secret
      - mosip_hotlist_client_secret
      - mosip_ida_client_secret
      - mosip_idrepo_client_secret
      - mosip_misp_client_secret
      - mosip_partner_client_secret
      - mosip_partnermanager_client_secret
      - mosip_pms_client_secret
      - mosip_policymanager_client_secret
      - mosip_prereg_client_secret
      - mosip_reg_client_secret
      - mosip_regproc_client_secret
      - mosip_resident_client_secret
      - mosip_syncdata_client_secret
      - mosip_testrig_client_secret
      - mpartner_default_auth_secret
      - mpartner_default_print_secret
      - mpartner_default_mobile_secret
      - mpartner_default_digitalcard_secret

- name: Create Vault secrets with random UUID content
  oracle.oci.oci_vault_secret:
    compartment_id: "{{ vault_compartment_id }}"
    vault_id: "{{ vault_id }}"
    key_id: "{{ vault_key_id }}"
    secret_name: "{{ item }}"
    secret_content:
      content_type: BASE64
      content: "{{ mosip_default_client_secret | b64encode }}"
  loop: "{{ secrets_list }}"
  loop_control:
    label: "{{ item }}"
  register: secret_creation_results

- name: Generate a list of secrets with default password
  set_fact:
    secrets_list:
      - mosip_pre_reg_captcha_secret_key
      - mosip_pre_reg_captcha_site_key
      - mosip_resident_captcha_site_key
      - mosip_resident_captcha_secret_key
      - mosip_esignet_captcha_site_key
      - mosip_esignet_captcha_secret_key
      - mimoto_oidc_partner_clientid
      - mosip_smtp_secret
      - mosip_sms_secret
      - mosip_minio_admin_password
      - mosip_pg_password
      - mosip_grafana_admin_password
      - mosip_keycloak_manager_password
      - mosip_keycloak_admin_password
      - mosip_activemq_password
      - mosip_esignet_misp_key
      - mosip_esignet_redis_password

- name: Create Vault secrets with default passsword
  oracle.oci.oci_vault_secret:
    compartment_id: "{{ vault_compartment_id }}"
    vault_id: "{{ vault_id }}"
    key_id: "{{ vault_key_id }}"
    secret_name: "{{ item }}"
    secret_content:
      content_type: BASE64
      content: "{{ mosip_default_password | b64encode }}"
  loop: "{{ secrets_list }}"
  loop_control:
    label: "{{ item }}"
  register: secret_creation_results


- name: Create Vault secrets for private lb subnetid
  oracle.oci.oci_vault_secret:
    compartment_id: "{{ vault_compartment_id }}"
    vault_id: "{{ vault_id }}"
    key_id: "{{ vault_key_id }}"
    secret_name: "mosip_private_lb_subnet_id"
    secret_content:
      content_type: BASE64
      content: "{{ private_lb_subnet_id | b64encode }}"

- name: Create Vault secrets for public subnetid
  oracle.oci.oci_vault_secret:
    compartment_id: "{{ vault_compartment_id }}"
    vault_id: "{{ vault_id }}"
    key_id: "{{ vault_key_id }}"
    secret_name: "mosip_public_lb_subnet_id"
    secret_content:
      content_type: BASE64
      content: "{{ public_lb_subnet_id | b64encode }}"

- name: Create Vault secrets for private lb nsg id
  oracle.oci.oci_vault_secret:
    compartment_id: "{{ vault_compartment_id }}"
    vault_id: "{{ vault_id }}"
    key_id: "{{ vault_key_id }}"
    secret_name: "mosip_private_lb_nsg_id"
    secret_content:
      content_type: BASE64
      content: "{{ private_lb_nsg_id | b64encode }}"

- name: Create Vault secrets for public lb nsg id
  oracle.oci.oci_vault_secret:
    compartment_id: "{{ vault_compartment_id }}"
    vault_id: "{{ vault_id }}"
    key_id: "{{ vault_key_id }}"
    secret_name: "mosip_public_lb_nsg_id"
    secret_content:
      content_type: BASE64
      content: "{{ public_lb_nsg_id | b64encode }}"

- name: Create Vault secrets for zone compartment_id
  oracle.oci.oci_vault_secret:
    compartment_id: "{{ vault_compartment_id }}"
    vault_id: "{{ vault_id }}"
    key_id: "{{ vault_key_id }}"
    secret_name: "mosip_zone_compartment_id"
    secret_content:
      content_type: BASE64
      content: "{{ zone_compartment_id | b64encode }}"       

- name: Create Vault secrets for domain
  oracle.oci.oci_vault_secret:
    compartment_id: "{{ vault_compartment_id }}"
    vault_id: "{{ vault_id }}"
    key_id: "{{ vault_key_id }}"
    secret_name: "mosip_domain"
    secret_content:
      content_type: BASE64
      content: "{{ domain | b64encode }}"  

- name: Create Vault secrets for domain ssl secret name
  oracle.oci.oci_vault_secret:
    compartment_id: "{{ vault_compartment_id }}"
    vault_id: "{{ vault_id }}"
    key_id: "{{ vault_key_id }}"
    secret_name: "mosip_domain_ssl_secret_name"
    secret_content:
      content_type: BASE64
      content: "{{ domain_ssl_secret_name | b64encode }}"  

- name: Create Vault secrets for region
  oracle.oci.oci_vault_secret:
    compartment_id: "{{ vault_compartment_id }}"
    vault_id: "{{ vault_id }}"
    key_id: "{{ vault_key_id }}"
    secret_name: "mosip_oci_region"
    secret_content:
      content_type: BASE64
      content: "{{ region | b64encode }}"  

- name: Create Vault secrets for tenancy id
  oracle.oci.oci_vault_secret:
    compartment_id: "{{ vault_compartment_id }}"
    vault_id: "{{ vault_id }}"
    key_id: "{{ vault_key_id }}"
    secret_name: "mosip_oci_tenancy_id"
    secret_content:
      content_type: BASE64
      content: "{{ tenancy_id | b64encode }}"  

- name: Create Vault secrets for acme stage
  oracle.oci.oci_vault_secret:
    compartment_id: "{{ vault_compartment_id }}"
    vault_id: "{{ vault_id }}"
    key_id: "{{ vault_key_id }}"
    secret_name: "acme_server_stage"
    secret_content:
      content_type: BASE64
      content: "{{ acme_server_stage | b64encode }}"  


- name: Create Vault secrets for acme prod
  oracle.oci.oci_vault_secret:
    compartment_id: "{{ vault_compartment_id }}"
    vault_id: "{{ vault_id }}"
    key_id: "{{ vault_key_id }}"
    secret_name: "acme_server_prod"
    secret_content:
      content_type: BASE64
      content: "{{ acme_server_prod | b64encode }}" 

- name: Create Vault secrets for hsm security pin
  oracle.oci.oci_vault_secret:
    compartment_id: "{{ vault_compartment_id }}"
    vault_id: "{{ vault_id }}"
    key_id: "{{ vault_key_id }}"
    secret_name: "mosip_softhsm_security_pin"
    secret_content:
      content_type: BASE64
      content: "{{ mosip_default_hsm_pin | b64encode }}" 


- name: Create Vault secrets for oidc keystore password
  oracle.oci.oci_vault_secret:
    compartment_id: "{{ vault_compartment_id }}"
    vault_id: "{{ vault_id }}"
    key_id: "{{ vault_key_id }}"
    secret_name: "mimoto_oidc_keystore_password"
    secret_content:
      content_type: BASE64
      content: "{{ mosip_default_mimoto_oidc_keystore_passsword | b64encode }}" 

- name: Create Vault secrets for mimoto partner api key
  oracle.oci.oci_vault_secret:
    compartment_id: "{{ vault_compartment_id }}"
    vault_id: "{{ vault_id }}"
    key_id: "{{ vault_key_id }}"
    secret_name: "mimoto_wallet_binding_partner_api_key"
    secret_content:
      content_type: BASE64
      content: "{{ mosip_default_dummy | b64encode }}" 

- name: Get region code
  oracle.oci.oci_identity_region_facts:
    name: "{{region}}"
  register: region_code

- name: Convert region key to lowercase and set as fact
  set_fact:
    region_key: "{{ region_code.regions[0].key | lower }}"


- name: Create container_repository for postgresql-client
  oracle.oci.oci_artifacts_container_repository:
    compartment_id: "{{compartment_id}}"
    display_name: mosip{{env}}/postgresql-client
    is_immutable: false
    is_public: false
  register: create_repo_pg_client

- name: Set image full path
  set_fact:
    postgresclient_image: "{{region_key}}.ocir.io/{{ create_repo_pg_client.container_repository.namespace }}/{{ create_repo_pg_client.container_repository.display_name }}"

- name: Pull PostgreSQL Client Docker image and push to ocir
  shell: |
    docker login {{region_key}}.ocir.io --username {{ create_repo_pg_client.container_repository.namespace }}/{{ocir_user}} --password '{{ocir_token}}'
    docker pull jbergknoff/postgresql-client
    docker tag jbergknoff/postgresql-client {{postgresclient_image}}
    docker push {{postgresclient_image}}
  register: docker_pull_result
  changed_when: "'Downloaded newer image' in docker_pull_result.stdout"

- name: Create container_repository for curl
  oracle.oci.oci_artifacts_container_repository:
    compartment_id: "{{compartment_id}}"
    display_name: mosip{{env}}/curl
    is_immutable: false
    is_public: false
  register: create_repo_curl

- name: Set image full path
  set_fact:
    curl_image: "{{region_key}}.ocir.io/{{ create_repo_curl.container_repository.namespace }}/{{ create_repo_curl.container_repository.display_name }}"

- name: Pull Curl Docker image and push to ocir
  shell: |
    docker login {{region_key}}.ocir.io --username {{ create_repo_curl.container_repository.namespace }}/{{ocir_user}} --password '{{ocir_token}}'
    docker pull registry.k8s.io/e2e-test-images/agnhost:2.39
    docker tag registry.k8s.io/e2e-test-images/agnhost:2.39 {{curl_image}}
    docker push {{curl_image}}
  register: docker_pull_result
  changed_when: "'Downloaded newer image' in docker_pull_result.stdout"

- name: Create Vault secrets for mosip_curl_image
  oracle.oci.oci_vault_secret:
    compartment_id: "{{ vault_compartment_id }}"
    vault_id: "{{ vault_id }}"
    key_id: "{{ vault_key_id }}"
    secret_name: "mosip_curl_image"
    secret_content:
      content_type: BASE64
      content: "{{ curl_image  | b64encode}}"

- name: Create Vault secrets for mosip_postgres_client_image
  oracle.oci.oci_vault_secret:
    compartment_id: "{{ vault_compartment_id }}"
    vault_id: "{{ vault_id }}"
    key_id: "{{ vault_key_id }}"
    secret_name: "mosip_postgres_client_image"
    secret_content:
      content_type: BASE64
      content: "{{ postgresclient_image  | b64encode}}"

- name: Creating docker secrets
  shell: "kubectl create secret docker-registry ocir --namespace default --docker-server {{region_key}}.ocir.io  --docker-username {{ create_repo_curl.container_repository.namespace }}/{{ocir_user}} --docker-password '{{ ocir_token }}' --dry-run=client -o=yaml | kubectl apply -f -"

- name: Get OCIR Docker config JSON from Kubernetes secret
  shell: |
    kubectl get secret ocir -n default -o jsonpath='{.data.\.dockerconfigjson}'
  register: ocir_config_encoded

- name: Decode OCIR Docker config JSON
  set_fact:
    ocir_config: "{{ ocir_config_encoded.stdout }}"

- name: Create Vault secrets for mosip_ocir_secret
  oracle.oci.oci_vault_secret:
    compartment_id: "{{ vault_compartment_id }}"
    vault_id: "{{ vault_id }}"
    key_id: "{{ vault_key_id }}"
    secret_name: "mosip_ocir_secret"
    secret_content:
      content_type: BASE64
      content: "{{ ocir_config }}"

- name: Removing k8s secret
  shell: "kubectl -n default delete secret ocir"

- name: Create regclient cert directories
  file:
    path: "{{item}}"
    state: directory
    mode: '0755'
  with_items:
    - /home/opc/regclient-setup


- name: "Copy deployment check script"
  copy:
    src: "{{item}}"
    dest: "/home/opc/regclient-setup/{{item}}"
    mode: "0755"
  with_items:
    - client-openssl.cnf
    - openssl.cnf
    - root-openssl.cnf
    - create-signing-certs.sh

- name: Check if regclient-certs ConfigMap exists
  command: kubectl get cm regclient-certs -n default
  register: regclient_cm
  ignore_errors: yes
  changed_when: false

- name: Create certificates
  shell: |
    bash create-signing-certs.sh {{regclient_keystore_password}}
    kubectl -n default create cm regclient-certs --from-file=./certs/
  args:
    chdir: /home/opc/regclient-setup
  when: regclient_cm.rc != 0

- name: Get keystore.p12 from regclient-certs ConfigMap
  shell: |
    kubectl get cm regclient-certs -n default -o jsonpath='{.binaryData.keystore\.p12}'
  register: keystore_p12
  ignore_errors: yes

- name: Set fact for keystore.p12
  set_fact:
    mosip_regclient_keystore_file: "{{ keystore_p12.stdout }}"

- name: Get Client.crt from regclient-certs ConfigMap
  shell: |
    kubectl get cm regclient-certs -n default -o jsonpath='{.data.Client\.crt}'
  register: clientcrt
  ignore_errors: yes

- name: Set fact for Client.crt
  set_fact:
    mosip_regclient_client_certificate: "{{ clientcrt.stdout | b64encode }}"

- name: Get Client.csr from regclient-certs ConfigMap
  shell: |
    kubectl get cm regclient-certs -n default -o jsonpath='{.data.Client\.csr}'
  register: clientcsr
  ignore_errors: yes

- name: Set fact for Client.csr
  set_fact:
    mosip_regclient_client_csr: "{{ clientcsr.stdout | b64encode  }}"

- name: Get Client.key from regclient-certs ConfigMap
  shell: |
    kubectl get cm regclient-certs -n default -o jsonpath='{.data.Client\.key}'
  register: clientkey
  ignore_errors: yes

- name: Set fact for Client.key
  set_fact:
    mosip_regclient_client_key: "{{ clientkey.stdout | b64encode }}"

- name: Get RootCA.crt from regclient-certs ConfigMap
  shell: |
    kubectl get cm regclient-certs -n default -o jsonpath='{.data.RootCA\.crt}'
  register: rootcacrt
  ignore_errors: yes

- name: Set fact for RootCA.crt
  set_fact:
    mosip_regclient_root_certificate: "{{ rootcacrt.stdout | b64encode }}"

- name: Get RootCA.key from regclient-certs ConfigMap
  shell: |
    kubectl get cm regclient-certs -n default -o jsonpath='{.data.RootCA\.key}'
  register: rootcakey
  ignore_errors: yes

- name: Set fact for RootCA.key
  set_fact:
    mosip_regclient_root_key: "{{ rootcakey.stdout | b64encode }}"


- name: Create Vault secrets for regclient_keystore_password
  oracle.oci.oci_vault_secret:
    compartment_id: "{{ vault_compartment_id }}"
    vault_id: "{{ vault_id }}"
    key_id: "{{ vault_key_id }}"
    secret_name: "mosip_regclient_keystore_password"
    secret_content:
      content_type: BASE64
      content: "{{ regclient_keystore_password | b64encode }}" 

- name: Create Vault secrets for mosip_regclient_keystore_file
  oracle.oci.oci_vault_secret:
    compartment_id: "{{ vault_compartment_id }}"
    vault_id: "{{ vault_id }}"
    key_id: "{{ vault_key_id }}"
    secret_name: "mosip_regclient_keystore_file"
    secret_content:
      content_type: BASE64
      content: "{{ mosip_regclient_keystore_file }}" 

- name: Create Vault secrets for mosip_regclient_client_certificate
  oracle.oci.oci_vault_secret:
    compartment_id: "{{ vault_compartment_id }}"
    vault_id: "{{ vault_id }}"
    key_id: "{{ vault_key_id }}"
    secret_name: "mosip_regclient_client_certificate"
    secret_content:
      content_type: BASE64
      content: "{{ mosip_regclient_client_certificate }}"

- name: Create Vault secrets for mosip_regclient_client_csr
  oracle.oci.oci_vault_secret:
    compartment_id: "{{ vault_compartment_id }}"
    vault_id: "{{ vault_id }}"
    key_id: "{{ vault_key_id }}"
    secret_name: "mosip_regclient_client_csr"
    secret_content:
      content_type: BASE64
      content: "{{ mosip_regclient_client_csr }}"

- name: Create Vault secrets for mosip_regclient_client_key
  oracle.oci.oci_vault_secret:
    compartment_id: "{{ vault_compartment_id }}"
    vault_id: "{{ vault_id }}"
    key_id: "{{ vault_key_id }}"
    secret_name: "mosip_regclient_client_key"
    secret_content:
      content_type: BASE64
      content: "{{ mosip_regclient_client_key }}"

- name: Create Vault secrets for mosip_regclient_root_certificate
  oracle.oci.oci_vault_secret:
    compartment_id: "{{ vault_compartment_id }}"
    vault_id: "{{ vault_id }}"
    key_id: "{{ vault_key_id }}"
    secret_name: "mosip_regclient_root_certificate"
    secret_content:
      content_type: BASE64
      content: "{{ mosip_regclient_root_certificate }}"

- name: Create Vault secrets for mosip_regclient_root_key
  oracle.oci.oci_vault_secret:
    compartment_id: "{{ vault_compartment_id }}"
    vault_id: "{{ vault_id }}"
    key_id: "{{ vault_key_id }}"
    secret_name: "mosip_regclient_root_key"
    secret_content:
      content_type: BASE64
      content: "{{ mosip_regclient_root_key }}"


