regclient_keystore_file: <path:ocivault#mosip_regclient_keystore_file#latest>
regclient_keystore_password: <path:ocivault#mosip_regclient_keystore_password#latest>
regclient_client_certificate: <path:ocivault#mosip_regclient_client_certificate#latest | base64decode>
regclient_client_csr: <path:ocivault#mosip_regclient_client_csr#latest | base64decode>
regclient_client_key: <path:ocivault#mosip_regclient_client_key#latest | base64decode>
regclient_root_certificate: <path:ocivault#mosip_regclient_root_certificate#latest | base64decode>
regclient_root_key: <path:ocivault#mosip_regclient_root_key#latest | base64decode>

initcontainer:
  curl_image: <path:ocivault#mosip_curl_image#latest | base64decode> 
  imagepullsecret: "ocir"
  artifactory_ns: artifactory

regclient:
  fullnameOverride: "regclient"
  regclient:
    upgradeServerUrl: https://regclient.<path:ocivault#mosip_domain#latest | base64decode>
    hostName: api-internal.<path:ocivault#mosip_domain#latest | base64decode>
    ## Here we check the health of syncdata service. The service must be accessible over internal channel.
    healthCheckUrl: https://api-internal.<path:ocivault#mosip_domain#latest | base64decode>/v1/syncdata/actuator/health
  istio:
    ingressController:
      name: ingressgateway-internal
    host: regclient.<path:ocivault#mosip_domain#latest | base64decode>

