zone_compartment_id: "{{compartment_id}}"
obs_kubeconfig_path: /home/opc/.kube/oke_obs_config
oke_k8s_cluster_endpoint: https://kubernetes.default.svc
oke_k8s_destination_name: mosip
env: dev
istio_chart_version: 1.23.2
avp_version: 1.20.0
acme_server_stage: https://acme-staging-v02.api.letsencrypt.org/directory
acme_server_prod: https://acme-v02.api.letsencrypt.org/directory
application_repo: https://github.com/oci-mosip/public-mosip-gitops
application_revision: mosip-document
certmanager_chart_version: 1.15.3
keycloak_chart_version: 20.0.0
rancher_chart_version: 2.11.0-rc8     ## should pick a version which is oke version compatible
certmanager_webhook_oci_chart_version: 1.2.1
longhorn_chart_version: 1.8.0
reloader_chart_version: 1.1.0
reflector_chart_version: 7.1.288
nginx_ingress_controller_chart_version: 4.10.0
keycloak_admin_password: changeme1234
keycloak_db_passsword: changeme1234
postgres_password: changeme1234
rancher_admin_password: changeme1234   # keeping 12 character
argcd_admin_password: changeme1234