initcontainer:
  curl_image: <path:ocivault#mosip_curl_image#latest | base64decode> 
  imagepullsecret: "ocir"
  registrycred: <path:ocivault#mosip_ocir_secret#latest> 

partner-onboarder:
  fullnameOverride: "partner-onboarder"
  onboarding:
    modules:
      - name: ida
        enabled: true
      - name: print
        enabled: true
      - name: abis
        enabled: true
      - name: resident
        enabled: true
      - name: mobileid
        enabled: true
      - name: digitalcard
        enabled: true

    configmaps:
      s3:
        # s3-host: 'https://minio.<path:ocivault#mosip_domain#latest | base64decode>'
        s3-user-key: 'admin'
        s3-region: 'us-east-1'
        s3-bucket-name: 'onboarder'
      onboarder-namespace:
        ns_mimoto: mimoto
        ns_esignet: esignet
    secrets: