apiVersion: v1
kind: ConfigMap
metadata:
  name: activemq-activemq-artemis-share
  namespace: {{ .Values.namespace }}
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "config-server"
data:
  activemq-core-port: {{ .Values.activemq.port | quote }}
  activemq-host: {{ .Values.activemq.host | quote }}