apiVersion: v1
kind: Secret
metadata:
  name: activemq-activemq-artemis
  namespace: {{ .Values.namespace }}
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "config-server"
data:
  artemis-password: {{ .Values.activemq.password | b64enc | quote }}
