apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: 'true'
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: 'true'
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "kernel"
  name: artifactory-jdk11-share
  namespace: {{ .Values.namespace }}
data:
  artifactory_url_env: http://artifactory.artifactory-jdk11:80
  auth_wrapper_url_env: http://artifactory.artifactory-jdk11:80/artifactory/libs-release-local/idp/idp-auth-wrapper/authentication-wrapper.jar
  cache_provider_url_env: http://artifactory.artifactory-jdk11:80/artifactory/libs-release-local/cache/cache-provider.jar
  esignet_wrapper_url_env: http://artifactory.artifactory-jdk11:80/artifactory/libs-release-local/esignet/esignet-wrapper.zip
  iam_adapter_regproc_ext_url_env: http://artifactory.artifactory-jdk11:80/artifactory/libs-release-local/io/mosip/kernel/kernel-auth-adapter.jar
  iam_adapter_regproc_url_env: http://artifactory.artifactory-jdk11:80/artifactory/libs-release-local/io/mosip/kernel/kernel-auth-adapter.jar
  iam_adapter_url_env: http://artifactory.artifactory-jdk11:80/artifactory/libs-release-local/io/mosip/kernel/kernel-auth-adapter.jar
  icu4j_url_env: http://artifactory.artifactory-jdk11:80/artifactory/libs-release-local/icu4j/icu4j.jar
  kernel_ref_idobjectvalidator_url: http://artifactory.artifactory-jdk11:80/artifactory/libs-release-local/io/mosip/kernel/kernel-ref-idobjectvalidator/java21/kernel-ref-idobjectvalidator.jar
  kernel_transliteration_icu4j_url_env: http://artifactory.artifactory-jdk11:80/artifactory/libs-release-local/icu4j/kernel-transliteration-icu4j.jar
  preregistration_i18n_bundle_url_env: http://artifactory.artifactory-jdk11:80/artifactory/libs-release-local/i18n/pre-registration-i18n-bundle.zip
  regproc_jars_env: /artifactory/libs-release-local/clamav/kernel-virusscanner-clamav.jar
  residentBundleUrl_env: http://artifactory.artifactory-jdk11:80/artifactory/libs-release-local/i18n/resident-i18n-bundle.zip
  runtime_dep_url_env: http://artifactory.artifactory-jdk11:80/artifactory/libs-release-local/io/mosip/kernel/
  virusscanner_url_env: http://artifactory.artifactory-jdk11:80/artifactory/libs-release-local/clamav/kernel-virusscanner-clamav.jar
  zip_file_path: /artifactory/libs-release-local/hsm/client.zip