apiVersion: v1
kind: ConfigMap
metadata:
  name: mockid-postgres-config
  namespace: {{ .Values.namespace }}
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "esignet"
data:
  database-host: {{ .Values.db.database_host | quote }}
  database-port: {{ .Values.db.database_port | quote }}
  database-name : {{ .Values.db.mock_id_db_name | quote }}
  database-username : {{ .Values.db.mock_id_username | quote }}
