apiVersion: v1
kind: Secret
metadata:
  name: postgres-postgresql
  namespace: {{ .Values.namespace }}
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "keycloak,esignet-postgres-init,inji,regproc"
type: Opaque
data:
  password: {{ .Values.keycloak.db_password | b64enc | quote }}
  postgres-password: {{ .Values.db.common_password | b64enc | quote }}

---

apiVersion: v1
kind: Secret
metadata:
  name: db-common-secrets
  namespace: {{ .Values.namespace }}
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "config-server,keymanager,masterdata-loader,esignet-postgres-init,esignet,regproc"
data:
  db-dbuser-password: {{ .Values.db.common_password | b64enc | quote }}
