apiVersion: v1
kind: ConfigMap
metadata:
  name: esignet-host
  namespace: {{ .Values.namespace }}
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "mimoto"
data:
  esignet-external-url: https://esignet.{{ .Values.domain_name }}