apiVersion: v1
kind: Secret
metadata:
  name: mosip-captcha
  namespace: {{ .Values.namespace }}
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "config-server"
data:
  prereg-captcha-site-key: {{ .Values.mosip.pre_reg_captcha_site_key | b64enc | quote }}
  prereg-captcha-secret-key: {{ .Values.mosip.pre_reg_captcha_secret_key | b64enc | quote }}
  resident-captcha-site-key: {{ .Values.mosip.resident_captcha_site_key | b64enc | quote }}
  resident-captcha-secret-key: {{ .Values.mosip.resident_captcha_secret_key | b64enc | quote }}
  esignet-captcha-site-key: {{ .Values.mosip.esignet_captcha_site_key | b64enc | quote }}
  esignet-captcha-secret-key: {{ .Values.mosip.esignet_captcha_secret_key | b64enc | quote }}

--- 

apiVersion: v1
kind: Secret
metadata:
  name: esignet-misp-onboarder-key
  namespace: {{ .Values.namespace }}
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "config-server"
data:
  mosip-esignet-misp-key: {{ .Values.mosip.mosip_esignet_misp_key | b64enc | quote }}

---

apiVersion: v1
kind: Secret
metadata:
  name: mimoto-wallet-binding-partner-api-key
  namespace: {{ .Values.namespace }}
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "config-server"
data:
  mimoto-wallet-binding-partner-api-key: {{ .Values.mosip.mosip_mimoto_wallet_binding_partner_api_key | b64enc | quote }}

---

apiVersion: v1
kind: Secret
metadata:
  name: mimoto-oidc-keystore-password
  namespace: {{ .Values.namespace }}
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "config-server"
data:
  mimoto-oidc-keystore-password: {{ .Values.mosip.mosip_mimoto_oidc_keystore_password | b64enc | quote }}

--- 

apiVersion: v1
kind: Secret
metadata:
  name: mimoto-oidc-partner-clientid
  namespace: {{ .Values.namespace }}
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "config-server"
data:
  mimoto-oidc-partner-clientid: {{ .Values.mosip.mimoto_oidc_partner_clientid | b64enc | quote }}