apiVersion: v1
kind: ConfigMap
metadata:
  name: msg-gateway
  namespace: {{ .Values.namespace }}
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "config-server"
data:
  sms-host: {{ .Values.msg_gateway.sms_host }}
  sms-port: {{ .Values.msg_gateway.sms_port | quote }}
  sms-username: {{ .Values.msg_gateway.sms_username }}
  smtp-host: {{ .Values.msg_gateway.smtp_host }}
  smtp-port: {{ .Values.msg_gateway.smtp_port | quote}}
  smtp-username: {{ .Values.msg_gateway.smtp_username }}

---
apiVersion: v1
kind: Secret
metadata:
  name: msg-gateway
  namespace: {{ .Values.namespace }}
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "config-server"
stringData:
  smtp-secret: {{ .Values.msg_gateway.smtp_secret }}
  sms-secret: {{ .Values.msg_gateway.sms_secret }}
  sms-authkey: {{ .Values.msg_gateway.sms_secret }}
