apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: ocir
  namespace: {{ .Values.namespace }}
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "config-server,keymanager,kernel,keymanager,mock-smtp,websub,masterdata-loader,packetmanager,biosdk,datashare,prereg,idrepo,abis,pms,regproc,admin,mosip-file-server,resident,regclient,esignet,mimoto,inji,onboarder"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.registrycred }}