apiVersion: v1
kind: Secret
metadata:
  name: redis
  namespace: {{ .Values.namespace }}
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "config-server"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "config-server"
data:
  redis-password: {{ .Values.esignet.redis_password | b64enc | quote }}
  redis-host: {{ .Values.esignet.redis_host | b64enc | quote }}