apiVersion: v1
kind: ConfigMap
metadata:
  name: s3
  namespace: {{ .Values.namespace }}
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "config-server"
data:
  s3-user-key: {{ .Values.minio.auth.rootUser }}  
  s3-region: {{ .Values.minio.region | quote }}  

---
apiVersion: v1
kind: Secret
metadata:
  name: s3
  namespace: {{ .Values.namespace }}
  annotations:
    avp.kubernetes.io/path: "ocivault"
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "config-server,esignet,mimoto,inji"
stringData:
  s3-user-secret: {{ .Values.minio.auth.rootPassword }}  
  s3-pretext-value: {{ .Values.minio.pretext_value }}  
