apiVersion: v1
kind: Secret
metadata:
  name: softhsm-kernel
  namespace: {{ .Values.namespace }}
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "config-server"
data:
  security-pin: {{ .Values.softhsm.kernel_securitypin | b64enc | quote}}

--- 

apiVersion: v1
kind: Secret
metadata:
  name: softhsm-esignet
  namespace: {{ .Values.namespace }}
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "config-server"
data:
  security-pin: {{ .Values.softhsm.esignet_securitypin | b64enc | quote }}

---

apiVersion: v1
kind: Secret
metadata:
  name: softhsm-mock-id-system
  namespace: {{ .Values.namespace }}
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "config-server"
data:
  security-pin: {{ .Values.softhsm.mockid_securitypin | b64enc | quote }}

--- 

apiVersion: v1
kind: Secret
metadata:
  name: softhsm-ida
  namespace: {{ .Values.namespace }}
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "config-server"
data:
  security-pin: {{ .Values.softhsm.ida_securitypin | b64enc | quote }}


---

apiVersion: v1
kind: Secret
metadata:
  name: softhsm-mock-identity-system
  namespace: {{ .Values.namespace }}
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "esignet"
data:
  security-pin: {{ .Values.softhsm.mockid_securitypin | b64enc | quote }}

---

apiVersion: v1
kind: Secret
metadata:
  name: softhsm-certify
  namespace: {{ .Values.namespace }}
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "config-server"
data:
  security-pin: {{ .Values.softhsm.certify_securitypin | b64enc | quote }}