kind: Application
metadata:
  name: demo-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    name: mosipdoc
  project: mosipdoc
  source:
    repoURL: 'https://github.com/ddevadat/public-mosip-gitops.git'
    targetRevision: mosip-document
    path: workload/mosip/external-modules/demo
  syncPolicy:
    syncOptions:
      - CreateNameSpace=true
      - ApplyOutOfSyncOnly=true
    automated:
      prune: true
      selfHeal: true