initcontainer:
  curl_image: <path:ocivault#mosip_curl_image#latest | base64decode> 
  imagepullsecret: "ocir"
  artifactory_ns: artifactory


admin-hotlist:
  fullnameOverride: "admin-hotlist"

admin-service:
  fullnameOverride: "admin-service"
  istio:
    corsPolicy:
      allowOrigins:
        - prefix: https://admin.<path:ocivault#mosip_domain#latest | base64decode>

admin-ui:
  fullnameOverride: "admin-ui"
  admin:
    apiUrl: https://api-internal.<path:ocivault#mosip_domain#latest | base64decode>/v1/
  istio:
    ingressController:
      name: ingressgateway-internal
    hosts:
      - admin.<path:ocivault#mosip_domain#latest | base64decode>
