os_user: opc
avp_version: 1.20.0
acme_server_stage: https://acme-staging-v02.api.letsencrypt.org/directory
acme_server_prod: https://acme-v02.api.letsencrypt.org/directory
application_repo: https://github.com/oci-mosip/public-mosip-gitops
application_revision: mosip-document
istio_chart_version: 1.23.2
certmanager_chart_version: 1.15.3
certmanager_webhook_oci_chart_version: 1.2.1
longhorn_chart_version: 1.8.0
reloader_chart_version: 1.1.0
reflector_chart_version: 7.1.288
cnpg_chart_version: 0.22.1
rook_operator_chart_version: 1.15.6
rook_ceph_cluster_chart_version: 1.15.6
oke_k8s_destination_name: mosip
env: dev
domain_ssl_secret_name: "{{ domain | replace('.', '-') }}"
uuidgen_path: /usr/bin/uuidgen
mosip_default_client_secret: e497c740-3564-4436-9565-cebaa2b399fc
mosip_default_password: changeme1234
mosip_default_hsm_pin: 74395275
mosip_default_mimoto_oidc_keystore_passsword: mosip123
mosip_default_dummy: dummy
regclient_keystore_password: 'IkNQTisxN3W//Q=='
smtp_host: mock-smtp.mock-smtp
smtp_port: "8025"
smtp_user: mock-smtp.user
bootstrap_namespace: "config-server,artifactory,keymanager,websub,mock-smtp,kernel,masterdata-loader,biosdk,packetmanager,datashare,prereg,idrepo,pms,abis,regproc,admin,ida,print,mosip-file-server,resident,regclient"