env: "dev"
region: ""
home_region: ""
domain: ""
tenancy_id: "ocid1.tenancy.oc1..aaaaaaaa"
compartment_id: "ocid1.compartment.oc1..aaaaaaaa"
vault_id: "ocid1.vault.oc1...."
vault_enc_key_id: "ocid1.key.oc1..."
tags:
  {
    "Project": "MOSIP-Dev",
    "generic/owner": "FirstName-LastName",
  }
k8s_cluster_properties:
  cluster_name: mosipdev