apiVersion: v1
kind: Pod
metadata:
  name: dnsutils
spec:
  containers:
  - name: dnsutils
    image: bom.ocir.io/bmohs4mmcms7/mosip/dnsutil:2.39
    imagePullPolicy: IfNotPresent
  restartPolicy: Always